import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinCompose)
}

android {
    namespace 'com.crowdin.platform.example'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.crowdin.platform.example"
        minSdkVersion 23
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "AVAILABLE_LOCAL_LANGUAGE_CODES", '"en-US;uk-UA"'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig = true
        compose = true
    }

    packagingOptions {
        exclude 'META-INF/crowdin_release.kotlin_module'
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_1_8
    }
}

dependencies {
    implementation project(":crowdin")
    implementation(project(":crowdin-controls")) {
        exclude group: 'com.github.crowdin.mobile-sdk-android'
    }
    implementation project(":example-info")

    implementation libs.androidx.appcompat
    implementation libs.androidx.material
    implementation libs.androidx.constraintlayout

    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx

    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.ui
    implementation libs.androidx.ui.tooling.preview
    implementation libs.androidx.compose.material3
    implementation libs.androidx.activity.compose
    debugImplementation libs.androidx.ui.tooling

    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso.core
    androidTestImplementation libs.androidx.test.espresso.contrib
}