plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.kotlinCompose) apply false
}

ext {
    compileSdkVersion = 36
    minSdkVersion = 16
    targetSdkVersion = 36
}

task clean(type: Delete) {
    delete rootProject.buildDir
}