ignore:
  - "**/R.class"
  - "**/R$*.class"
  - "**/BuildConfig.*"
  - "**/Manifest.*"
  - "**/Test.*"
  - "android/**/.*"
  - "**/auth**"
  - "**/CrowdinContextWrapper.*"
  - "**/CrowdinLayoutInflater.*"
  - "**/CrowdinResources.*"
  - "**/Attributes.*"
  - "**/ThreadUtils.*"
  - "**/Extensions.*"
  - "**/ScreenshotService.*"
  - "**/Connectivity.*"
  - "**/NetworkType.*"
  - "**/api**"
  - "**/XmlParserUtils.*"
  - "**/BaseNavigationViewTransformer.*"
  - "**/BaseToolbarTransformer.*"
  - "**/BaseTransformer.*"
  - "**/BottomNavigationViewTransformer.*"
  - "**/NavigationViewTransformer.*"
  - "**/SpinnerTransformer.*"
  - "**/SupportToolbarTransformer.*"
  - "**/TextViewTransformer.*"
  - "**/ToolbarTransformer.*"
  - "**/ScreenshotUtils.*"