trigger:
  branches:
    include:
    - refs/heads/*
    exclude:
    - refs/tags/*
  paths:
    exclude:
    - README.md
    - LICENSE

jobs:
  - template: templates/jobs.yml
    parameters:
      name: Linux
      vmImage: 'ubuntu-latest'
